
const List<List<String>> builtinWordPairsRaw = [
  ['Kahve', 'Çay'],
  ['Deniz', 'Göl'],
  ['Elma', 'Armut'],
  ['Kitap', 'Dergi'],
  ['Doktor', 'Hemşire'],
  ['Uçak', 'Helikopter'],
  ['Tren', 'Metro'],
  ['Piyano', 'Org'],
  ['Futbol', 'Hentbol'],
  ['Kedi', 'Aslan'],
  ['Köpek', 'Kurt'],
  ['Gitar', 'Bağlama'],
  ['Pizza', 'Lahmacun'],
  ['Portakal', 'Mandalina'],
  ['Bilgisayar', 'Tablet'],
  ['Cep telefonu', 'Akıllı saat'],
  ['Yağmur', 'Kar'],
  ['Deprem', 'Sel'],
  ['Ay', 'Yıldız'],
  ['Güneş', 'Ateş'],
  ['Nehir', 'Dere'],
  ['Dağ', 'Tepe'],
  ['Orman', 'Bahçe'],
  ['Çöl', 'Bozkır'],
  ['Balık', 'Yunus'],
  ['Kuş', 'Yarasa'],
  ['Arı', 'Eşek arısı'],
  ['Kelebek', 'Güve'],
  ['Karınca', 'Termit'],
  ['Gül', 'Lale'],
  ['Papatya', 'Ayçiçeği'],
  ['Çam', 'Selvi'],
  ['Meşe', 'Kayın'],
  ['Şeker', 'Bal'],
  ['Tuz', 'Karabiber'],
  ['Ekmek', 'Simit'],
  ['Peynir', 'Lor'],
  ['Süt', 'Ayran'],
  ['Yumurta', 'Omlet'],
  ['Makarna', 'Erişte'],
  ['Pilav', 'Bulgur'],
  ['Çorba', 'Consomme'],
  ['Salata', 'Meze'],
  ['Dondurma', 'Sütlaç'],
  ['Baklava', 'Künefe'],
  ['Çikolata', 'Gofret'],
  ['Bisiklet', 'Motosiklet'],
  ['Otomobil', 'Kamyonet'],
  ['Gemi', 'Yelkenli'],
  ['Vapur', 'Feribot'],
  ['Otobüs', 'Minibüs'],
  ['Taksi', 'Dolmuş'],
  ['Köprü', 'Viyadük'],
  ['Kule', 'Minare'],
  ['Cami', 'Kilise'],
  ['Müze', 'Galeri'],
  ['Kütüphane', 'Arşiv'],
  ['Hastane', 'Klinik'],
  ['Eczane', 'Market'],
  ['Otel', 'Pansiyon'],
  ['Restoran', 'Kafe'],
  ['Sinema', 'Tiyatro'],
  ['Stadyum', 'Spor salonu'],
  ['Havalimanı', 'Liman'],
  ['İstasyon', 'Durak'],
  ['Okul', 'Kurs'],
  ['Üniversite', 'Akademi'],
  ['Sınıf', 'Amfi'],
  ['Öğretmen', 'Eğitmen'],
  ['Öğrenci', 'Kursiyer'],
  ['Kalem', 'Tükenmez kalem'],
  ['Silgi', 'Düzeltme kalemi'],
  ['Defter', 'Ajanda'],
  ['Çanta', 'Sırt çantası'],
  ['Gözlük', 'Güneş gözlüğü'],
  ['Şapka', 'Bere'],
  ['Ayakkabı', 'Terlik'],
  ['Bot', 'Sandalet'],
  ['Ceket', 'Mont'],
  ['Kazak', 'Hırka'],
  ['Gömlek', 'Tişört'],
  ['Pantolon', 'Şort'],
  ['Etek', 'Elbise'],
  ['Eldiven', 'Atkı'],
  ['Yüzük', 'Bilezik'],
  ['Kolye', 'Küpe'],
  ['Saat', 'Çalar saat'],
  ['Ayna', 'Cam'],
  ['Masa', 'Sehpa'],
  ['Sandalye', 'Koltuk'],
  ['Yatak', 'Kanepe'],
  ['Dolap', 'Vitrin'],
  ['Halı', 'Kilim'],
  ['Perde', 'Jaluzi'],
  ['Lamba', 'Avize'],
  ['Buzdolabı', 'Derin dondurucu'],
  ['Fırın', 'Mikrodalga'],
  ['Çamaşır makinesi', 'Bulaşık makinesi'],
  ['Süpürge', 'Elektrikli süpürge'],
  ['Tencere', 'Tava'],
  ['Bıçak', 'Makas'],
  ['Kaşık', 'Çatal'],
  ['Tabak', 'Kase'],
  ['Bardak', 'Fincan'],
  ['Termos', 'Matara'],
  ['Çekiç', 'Tornavida'],
  ['Testere', 'Matkap'],
  ['Merdiven', 'İskele'],
  ['Anahtar', 'Kilit'],
  ['Ampul', 'Fener'],
  ['Pil', 'Şarj cihazı'],
  ['Kulaklık', 'Hoparlör'],
  ['Kamera', 'Fotoğraf makinesi'],
  ['Televizyon', 'Projeksiyon'],
  ['Radyo', 'Walkie-talkie'],
  ['Yazıcı', 'Tarayıcı'],
  ['Klavye', 'Fare'],
  ['Internet', 'Wi-Fi'],
  ['Uygulama', 'Web sitesi'],
  ['Oyun', 'Bulmaca'],
  ['Satranç', 'Dama'],
  ['Zar', 'İskambil'],
  ['Bahçe', 'Park'],
  ['Salıncak', 'Kaydırak'],
  ['Havuz', 'Jakuzi'],
  ['Plaj', 'Kumsal'],
  ['Dalgıç', 'Yüzücü'],
  ['Sörf', 'Kürek'],
  ['Kayak', 'Snowboard'],
  ['Paten', 'Kaykay'],
  ['Koşu', 'Yürüyüş'],
  ['Yoga', 'Pilates'],
  ['Boks', 'Güreş'],
  ['Tenis', 'Masa tenisi'],
  ['Voleybol', 'Plaj voleybolu'],
  ['Basketbol', 'Streetball'],
  ['Bowling', 'Bilardo'],
  ['Golf', 'Okçuluk'],
  ['Maraton', 'Triatlon'],
  ['Hakem', 'Antrenör'],
  ['Takım', 'Kulüp'],
  ['Kupa', 'Madalya'],
  ['Bilet', 'Davetiye'],
  ['Konser', 'Festival'],
  ['Orkestra', 'Koro'],
  ['Şarkı', 'Türkü'],
  ['Dans', 'Bale'],
  ['Ressam', 'Heykeltıraş'],
  ['Fırça', 'Palet'],
  ['Tuval', 'Kağıt'],
  ['Fotoğraf', 'Poster'],
  ['Mektup', 'Kartpostal'],
  ['Zarf', 'Paket'],
  ['Pul', 'Damga'],
  ['Para', 'Kredi kartı'],
  ['Cüzdan', 'Çanta'],
  ['Banka', 'Vezne'],
  ['Market', 'Bakkal'],
  ['Fabrika', 'Atölye'],
  ['Ofis', 'Büro'],
  ['Toplantı', 'Seminer'],
  ['Rapor', 'Sunum'],
  ['Fatura', 'Makbuz'],
  ['Polis', 'Jandarma'],
  ['İtfaiyeci', 'Kurtarma ekibi'],
  ['Asker', 'Subay'],
  ['Aşçı', 'Garson'],
  ['Berber', 'Kuaför'],
  ['Terzi', 'Ayakkabı tamircisi'],
  ['Çiftçi', 'Bahçıvan'],
  ['Balıkçı', 'Avcı'],
  ['Mühendis', 'Mimar'],
  ['Avukat', 'Hakim'],
  ['Gazeteci', 'Muhabir'],
  ['Yazar', 'Şair'],
  ['Fotoğrafçı', 'Kameraman'],
  ['Pilot', 'Kaptan'],
  ['Şoför', 'Kurye'],
];

/// Ham çift listesinden bir [WordPack] üretir.
List<List<String>> get builtinWordPairsSource => builtinWordPairsRaw;